[[redirects]]
from = "/registration"
to = "/registration/pre-registration/index.html"
status=200
force=true

[[redirects]]
from = "/registration/form"
to = "/registration/registration.html"
status=200
force=true

[[redirects]]
from = "/"
to = "index.html"
status=200
force=true

[[redirects]]
from = "/blog/sarvh"
to = "sarvh.html"
status=200
force=true

[[redirects]]
from = "/blog/sustainable"
to = "sustainable.html"
status=200
force=true